//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPubApp
{
    using System;
    using System.Collections.Generic;
    using WebPubApp.Common;


    public partial class Authorship
    {
        public int PersonID { get; set; }
        public int PMID { get; set; }
        public int BranchID { get; set; }
        public short Position { get; set; }
    
        public virtual OrgBranch OrgBranch { get; set; }
        public virtual Person Person { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
